import keyMirror from 'keymirror';

export default keyMirror({
	PLAYGROUND_INPUT_UPDATED: null,
	PLAYGROUND_START_PROCESS_INPUT: null,

	PLAYGROUND_KEYBOARD_ACTION: null,

	PLAYGROUND_SET_POSTCSS_CSS_VARIABLES_PRESERVE: null,

	PLAYGROUND_SET_SHOULD_LIVE_RELOAD: null,
	PLAYGROUND_SET_TAB_WIDTH: null
});